
name: frontend ec2 deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: connect to ec2
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
          FIRST_WEEK_KEY: ${{secrets.}}

        run: |
          ssh -i "first-key.pem" ec2-user@ec2-3-10-117-124.eu-west-2.compute.amazonaws.com
